'''
Primarily there are two types of loops in python. Loops are used to execute a block of code repeatedly until a certain condition is met. The two types of loops in Python are:
1) while loops
2) for loops
'''


print(1)
print(2)
print(3)
print(4)
print(5)

# The same task can be done like this:
for i in range(1, 6): # Range function generates a sequence of numbers from 0 to (n-1) by default, but we can specify the start and end values.
    print(i)